version: '3.8'

services:

  selenium_service:
    image: selenium/standalone-chrome
    container_name: container_selenium
    environment:
      VNC_NO_PASSWORD: 1
    shm_size: 2gb
    ports:
      - 4444:4444

  service_splash:
    image: scrapinghub/splash
    container_name: container_splash
    command: --maxrss 2048 --max-timeout 300 --disable-lua-sandbox --verbosity 1
    ports:
      - "8050:8050"
    restart: unless-stopped