version: '3.8'

services:

  postgres_service:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'

  selenium_service:
    image: selenium/standalone-chrome
    container_name: container_selenium
    environment:
      VNC_NO_PASSWORD: 1
    shm_size: 2gb
    ports:
      - 4444:4444
